name: Python Test

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.8
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r "../../day5/models/random_forest.pkl"/day5/requirements.txt

      # Run pytest tests
      - name: Run tests
        env:
          RF_MODEL: ${{vars.RF_MODEL}}
          LOGISTIC_MODEL: ${{vars.LOGISTIC_MODEL}}
        run: pytest ./day5/tests/test_main.py
      - name: Extract and Print Secret
        env:
          SECRET_PASS: ${{ secrets.SECRET_PASS }}
        run: |
          echo "Extracted Secret (visible): $SECRET_PASS"
