name: Python Test

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run pytest tests
      - name: Run tests
        run: pytest ./day5/tests/test_main.py
